<?php

return [
    'app' => [
        'name' => 'Polonads Mailing App',
        'base_url' => '/mailing_app/public',
        'public_url' => 'https://example.com/mailing_app/public',
        'polonads_listing_url_template' => 'https://polonads.com/index.php/en-us/ad/{id}:{alias}',
        'upload_dir' => __DIR__ . '/../storage/uploads',
        'timezone' => 'Europe/Warsaw',
        'response_secret' => 'change-this-secret-token',
        'require_click_confirmation' => false,
        'self_publish_url' => 'https://polonads.com/index.php/en-us/dodajogloszenie-2',
        'account_login_url' => 'https://polonads.com/index.php/en-us/login',
        'account_setup_url' => 'https://polonads.com/index.php/en-us/reset-password',
    ],
    'db' => [
        'host' => 'localhost',
        'port' => 3306,
        'database' => 'polonads_mailing',
        'username' => 'db_user',
        'password' => 'db_password',
        'charset' => 'utf8mb4',
    ],
    'polonads_db' => [
        'host' => 'localhost',
        'port' => 3306,
        'database' => 'polojrre_joom547',
        'username' => 'polonads_user',
        'password' => 'polonads_password',
        'charset' => 'utf8mb4',
        'prefix' => 'jost3_',
    ],
    'mail' => [
        'host' => 'polonads.com',
        'port' => 465,
        'username' => 'alex@polonads.com',
        'password' => 'email_password',
        'from_email' => 'alex@polonads.com',
        'from_name' => 'Alex | Polonads',
        'use_ssl' => true,
        'use_tls' => false,
        'connect_timeout' => 20,
        'delivery_mode' => 'redirect',
        'redirect_to_email' => 'eskey69@gmail.com',
        'redirect_subject_prefix' => '[TEST MAILING] ',
        'pause_seconds' => 90,
        'batch_size' => 3,
    ],
    'automation' => [
        'open_tracking_enabled' => true,
        'open_followup_delay_days' => 3,
        'unopened_followup_delay_days' => 7,
        'contact_later_followup_delay_days' => 14,
        'cold_max_attempts_before_cooldown' => 3,
        'cooldown_retry_days' => 14,
    ],
    'publication' => [
        'batch_size' => 5,
        'pause_seconds' => 15,
    ],
    'photo_library' => [
        'source_url' => 'https://polonads.com/images/kategorie',
        'source_path' => '/home/ACCOUNT/public_html/images/kategorie',
        'max_depth' => 2,
        'extensions' => ['jpg', 'jpeg', 'png', 'webp'],
        'category_folders' => [
            3 => '3_dam_prace',
            4 => '4_uslugi',
            5 => '5_budowa_i_remonty',
            6 => '6_transport_i_przeprowadzki',
            9 => '9_it_i_internet',
            10 => '10_reklama_i_fotografia',
            11 => '11_opieka_i_pomoc_domowa',
            12 => '12_nauka_i_kursy',
            13 => '13_zdrowie_i_uroda',
            14 => '14_prawo_i_finanse',
            16 => '16_nieruchomosci',
            21 => '21_paczki_do_polski',
            22 => '22_ubezpieczenia',
            23 => '23_sprzedam_kupie_oddam',
            36 => '36_organizacje_spoleczne_i_religijne',
        ],
    ],
];
